import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import test from "node:test";

type RoadmapCase = {
  label: string;
  token: string;
};

const sourceFiles = [
  "README.md",
  "docs/SELF_BUILDING_LAB.md",
  "docs/SCIENTIFIC_METHOD.md",
  "package.json",
  "src/cli/index.ts",
  "src/core/lab/lab-service.ts",
  "src/core/science/science-service.ts",
  "src/core/corpus/corpus-product-service.ts",
];

let haystackPromise: Promise<string> | undefined;

async function haystack() {
  haystackPromise ??= Promise.all(
    sourceFiles.map((file) => readFile(join(process.cwd(), file), "utf8")),
  ).then((parts) => parts.join("\n"));
  return haystackPromise;
}

function casesFrom(prefix: string, tokens: string[]): RoadmapCase[] {
  return tokens.map((token) => ({
    label: `${prefix}: ${token}`,
    token,
  }));
}

const roadmap: Array<{
  week: string;
  minimum: number;
  cases: RoadmapCase[];
}> = [
  {
    week: "3.4.1 self-built lab study hardening",
    minimum: 40,
    cases: [
      ...casesFrom("command", [
        "sovryn lab study audit",
        "sovryn lab study harden",
        "sovryn lab memory report",
      ]),
      ...casesFrom("result kind", ["self_built_lab_science_study"]),
      ...casesFrom("hardening gate", [
        "SELF_BUILT_LAB_STUDIES_INDEXED",
        "SELF_BUILT_LAB_FALSIFICATION_EVALUATED",
        "SELF_BUILT_LAB_PEER_REVIEW_PRESENT",
        "INSTRUMENT_CALIBRATION_PUBLIC",
        "PIPELINE_REPLAY_PRESENT",
        "LAB_MEMORY_BOUND",
        "TOOLCHAIN_SUMMARY_PUBLIC_SAFE",
        "NO_UNSUPPORTED_SCIENTIFIC_CLAIMS",
        "PUBLIC_HYGIENE_PASSED",
      ]),
      ...casesFrom("public artifact", [
        "LAB_NEEDS.md",
        "BUILD_VS_BUY.md",
        "TOOLCHAIN.md",
        "INSTRUMENTS.md",
        "PIPELINE.md",
        "CALIBRATION.md",
        "FALSIFICATION.md",
        "PEER_REVIEW.md",
        "LAB_MEMORY_UPDATE.md",
        "SHOWCASE.md",
        "METHOD.md",
        "REPRODUCE.md",
        "EXAMPLES.md",
      ]),
      ...casesFrom("metadata field", [
        "falsificationStatus",
        "peerReviewPresent",
        "calibrationStatus",
        "instrumentCalibrationPresent",
        "pipelineReplayPresent",
        "labMemoryBound",
        "statisticalAnalysisPresent",
        "baselineComparisonPresent",
        "ablationPresent",
        "sensitivityPresent",
        "replicationRunCount",
        "scientificMemoryUpdated",
        "studyResultLabel",
        "showcaseDocumentation",
        "lifecycleStatus",
        "showcaseEligible",
      ]),
      ...casesFrom("status", [
        "showcase_science",
        "passes_falsification",
        "calibrated_limited",
        "superseded",
        "needs_revision",
      ]),
      ...casesFrom("aggregate", [
        "aggregate/lab-studies.json",
        "aggregate/lab-memory-summary.json",
        "public-corpus/api/science-studies.json",
        "VERIFICATION.md",
      ]),
    ],
  },
  {
    week: "3.4.2 new real-data self-built lab domain",
    minimum: 50,
    cases: [
      ...casesFrom("domain", [
        "scientific-dataset-reliability",
        "schema-drift",
        "public scientific dataset metadata",
        "safe public metadata",
      ]),
      ...casesFrom("science data command", [
        "sovryn science data search",
        "sovryn science data ingest",
        "sovryn science data validate",
        "sovryn science data provenance",
        "sovryn science data replay",
      ]),
      ...casesFrom("lab command", [
        "sovryn lab trial run",
        "--real-sources-preferred",
        "--real-data-preferred",
        "--autopublish-corpus",
      ]),
      ...casesFrom("instrument", [
        "schema-drift-detector",
        "provenance-quality-scorer",
        "dataset-record-auditor",
        "baseline-schema-validator",
      ]),
      ...casesFrom("package", [
        "jsonschema",
        "pandas",
        "python-dateutil",
        "rapidfuzz",
      ]),
      ...casesFrom("gate", [
        "NEW_DOMAIN_INCLUDED",
        "REAL_DATA_OR_PROXY_USED",
        "DATASET_PROVENANCE_PRESENT",
        "LAB_NEEDS_INFERRED",
        "BUILD_VS_BUY_DECISION_PRESENT",
        "TOOLCHAIN_PROVISIONING_ATTEMPTED",
        "CUSTOM_INSTRUMENT_BUILT_FOR_EACH_STUDY",
        "PIPELINE_COMPOSED_FOR_EACH_STUDY",
        "NODE_ALPHA_EXECUTION_PRESENT",
        "CONTAINER_NETOFF_USED_OR_DEGRADED_EXPLICITLY",
        "BASELINES_PRESENT",
        "STATISTICS_PRESENT",
        "REPLICATIONS_PRESENT",
        "FALSIFICATIONS_PRESENT",
        "LAB_MEMORY_UPDATED",
        "SCIENTIFIC_MEMORY_UPDATED",
      ]),
      ...casesFrom("data field", [
        "dataset title",
        "schema fields",
        "version timestamp",
        "source/provenance label",
        "unit metadata",
        "missingness flag",
        "duplicate record marker",
        "fixture labels",
      ]),
      ...casesFrom("safety", [
        "No private data",
        "medical patient data",
        "human-subject data",
        "hazardous bio/chem data",
        "exploit datasets",
      ]),
      ...casesFrom("artifact", [
        "real-data-summary.json",
        "scientific-memory-update.json",
        "selected-studies.json",
        "trial-scorecard.json",
        "REAL_SOURCE_SELF_BUILT_LAB_REPORT.md",
      ]),
    ],
  },
  {
    week: "3.4.3 lab memory reuse and capability graph",
    minimum: 55,
    cases: [
      ...casesFrom("command", [
        "sovryn lab memory report",
        "sovryn lab memory search",
        "sovryn lab memory recommend",
        "sovryn lab memory graph",
        "sovryn lab reuse plan",
        "sovryn lab reuse audit",
      ]),
      ...casesFrom("memory artifact", [
        "tool-registry.json",
        "package-registry.json",
        "instrument-registry.json",
        "pipeline-registry.json",
        "capability-graph.json",
        "failure-history.json",
        "reuse-recommendations.json",
        "LAB_MEMORY.md",
        "CAPABILITY_GRAPH.md",
        "REUSE_REPORT.md",
      ]),
      ...casesFrom("registry field", [
        "toolName",
        "packageName",
        "instrumentId",
        "pipelineId",
        "capability",
        "usedInStudy",
        "success",
        "calibrationStatus",
        "workerProfile",
        "reproducibilityStatus",
        "reuseRecommendation",
      ]),
      ...casesFrom("recommendation", [
        "strongly_reuse",
        "reuse_with_caution",
        "needs_calibration",
        "avoid",
        "obsolete",
        "reuse_when_capability_matches",
      ]),
      ...casesFrom("edge", [
        "instrument_provides_capability",
        "package_preferred_for_capability",
        "study_uses_pipeline",
        "instrument_failed_on_case",
      ]),
      ...casesFrom("gate", [
        "LAB_MEMORY_GRAPH_PRESENT",
        "REUSE_RECOMMENDATIONS_PRESENT",
        "BUILD_VS_BUY_USES_MEMORY",
        "FAILED_TOOLS_NOT_REUSED_UNCHECKED",
        "REUSED_INSTRUMENTS_CALIBRATED",
        "NEW_INSTRUMENT_BUILT_ONLY_IF_NEEDED",
        "REUSE_DECISION_RECORDED",
      ]),
      ...casesFrom("search capability", [
        "unit_normalization",
        "outlier_detection",
        "baseline_modeling",
        "replication_runner",
        "falsification_case_generation",
        "schema_validation",
        "provenance_scoring",
        "dependency_metadata_parsing",
      ]),
      ...casesFrom("memory behavior", [
        "Build-vs-buy must consult lab memory.",
        "Reused instruments must be calibrated.",
        "Failed tools must not be strongly reused without recalibration.",
        "Capability appears in the current lab-needs map",
        "prior memory has usable evidence",
        "Capability graph",
        "Lab Memory",
        "reuse plan",
        "reuse audit",
      ]),
    ],
  },
  {
    week: "3.4.4 instrument benchmarking and calibration",
    minimum: 65,
    cases: [
      ...casesFrom("command", [
        "sovryn lab instrument benchmark",
        "sovryn lab instrument benchmark-all",
        "sovryn lab instrument calibrate-all",
        "sovryn lab instrument rank",
        "sovryn lab instrument retire",
      ]),
      ...casesFrom("artifact", [
        "benchmark-suite.json",
        "benchmark-results.json",
        "calibration-results.json",
        "instrument-rankings.json",
        "retired-instruments.json",
        "INSTRUMENT_BENCHMARK_REPORT.md",
        "BENCHMARK.md",
        "CALIBRATION.md",
        "failure-taxonomy.json",
        "reuse-status.json",
      ]),
      ...casesFrom("status", [
        "calibrated",
        "calibrated_limited",
        "needs_calibration",
        "failed_calibration",
        "obsolete",
        "unsafe_scope_blocked",
      ]),
      ...casesFrom("benchmark category", [
        "unit_normalization",
        "outlier_detection",
        "provenance_scoring",
        "baseline_modeling",
        "falsification_case_generation",
        "replication_runner",
        "dependency_metadata_parsing",
        "schema_validation",
      ]),
      ...casesFrom("benchmark field", [
        "positiveCases",
        "negativeCases",
        "edgeCases",
        "falsePositiveCases",
        "falseNegativeCases",
        "baselineComparisonPresent",
        "deterministicOutput",
        "workerExecutionCheck",
        "failureTaxonomy",
        "reuseStatus",
        "publicSafe",
      ]),
      ...casesFrom("instrument", [
        "mol-record-auditor",
        "energy-record-auditor",
        "patch-risk-auditor",
        "schema-drift-detector",
        "baseline-comparator",
        "replication-runner",
        "falsification-case-generator",
      ]),
      ...casesFrom("gate", [
        "BENCHMARK_SUITE_PRESENT",
        "INSTRUMENTS_BENCHMARKED",
        "CALIBRATION_STATUS_PRESENT",
        "FAILURE_TAXONOMY_PRESENT",
        "REUSE_STATUS_UPDATED",
        "FAILED_INSTRUMENTS_NOT_STRONGLY_REUSED",
        "BENCHMARK_RESULTS_PUBLIC_SAFE",
      ]),
      ...casesFrom("rule", [
        "strongly_reuse",
        "needs_calibration",
        "failed_calibration",
        "cannot be used for showcase science",
        "superseded",
        "false_positive_edge_case",
        "false_negative_edge_case",
        "malformed_input",
        "container-netoff",
        "noSilentFallback",
        "exitCode",
        "retired",
        "rankedAt",
        "benchmarkCount",
        "calibrationCount",
        "score",
        "public safe",
      ]),
    ],
  },
  {
    week: "3.4.5 self-built lab reproduction challenge",
    minimum: 60,
    cases: [
      ...casesFrom("command", [
        "sovryn science reproduce search",
        "sovryn lab reproduce plan",
        "sovryn lab reproduce run",
        "sovryn lab reproduce analyze",
        "sovryn lab reproduce publish",
      ]),
      ...casesFrom("artifact", [
        "source-claim.md",
        "method-extraction.json",
        "data-requirements.json",
        "metric-requirements.json",
        "lab-needs.json",
        "build-vs-buy-decision.json",
        "instrument-reuse-plan.json",
        "reproduction-pipeline.json",
        "reproduction-run.json",
        "reproduction-analysis.json",
        "REPRODUCTION_REPORT.md",
        "LIMITATIONS.md",
      ]),
      ...casesFrom("result type", ["self_built_lab_reproduction"]),
      ...casesFrom("label", [
        "reproduced",
        "partially_reproduced",
        "not_reproduced",
        "inconclusive",
        "unsafe_scope_blocked",
      ]),
      ...casesFrom("gate", [
        "SOURCE_CLAIM_EXTRACTED",
        "METHOD_EXTRACTED",
        "DATA_REQUIREMENTS_PRESENT",
        "METRIC_REQUIREMENTS_PRESENT",
        "LAB_NEEDS_INFERRED",
        "BUILD_VS_BUY_DECISION_PRESENT",
        "PIPELINE_COMPOSED",
        "NODE_ALPHA_EXECUTION_PRESENT",
        "REPRODUCTION_ANALYSIS_PRESENT",
        "NO_OVERCLAIMED_REPRODUCTION",
        "LIMITATIONS_PRESENT",
        "PUBLIC_HYGIENE_PASSED",
      ]),
      ...casesFrom("safe topic", [
        "anomaly detection",
        "data quality",
        "dataset reliability",
        "schema drift",
        "software supply-chain",
        "risk scoring",
      ]),
      ...casesFrom("safety rule", [
        "no wet-lab",
        "medical",
        "hazardous",
        "exploit",
        "substitute data",
        "lowers confidence",
        "full reproduction",
        "method, data, and metrics",
        "bounded computational",
      ]),
      ...casesFrom("analysis field", [
        "sourceClaim",
        "methodExtraction",
        "dataRequirements",
        "metricRequirements",
        "methodMatch",
        "dataMatch",
        "metricMatch",
        "reproductionConfidence",
        "noOverclaimedReproduction",
        "nodeAlphaExecution",
        "workerProfile",
        "noSilentFallback",
      ]),
    ],
  },
  {
    week: "4.2.0-rc.1 real-source self-building lab trial",
    minimum: 100,
    cases: [
      ...casesFrom("command", [
        "sovryn lab trial run",
        "--studies 4",
        "--real-sources-preferred",
        "--real-data-preferred",
        "--autopublish-corpus",
      ]),
      ...casesFrom("trial artifact", [
        "trial-plan.json",
        "selected-questions.json",
        "selected-studies.json",
        "lab-needs-summary.json",
        "build-vs-buy-summary.json",
        "provisioning-summary.json",
        "instrument-summary.json",
        "pipeline-summary.json",
        "reproduction-summary.json",
        "node-alpha-summary.json",
        "real-data-summary.json",
        "lab-memory-update.json",
        "scientific-memory-update.json",
        "trial-scorecard.json",
        "REAL_SOURCE_SELF_BUILT_LAB_REPORT.md",
        "BLOCKERS.md",
      ]),
      ...casesFrom("domain", [
        "scientific dataset reliability",
        "energy anomaly detection",
        "software supply-chain assurance",
        "benchmark reproducibility",
        "public metadata quality",
        "open-data schema drift",
        "model-evaluation dataset robustness",
      ]),
      ...casesFrom("public type", [
        "self_built_lab_science_study",
        "self_built_lab_reproduction",
        "self_built_lab_negative_result",
        "self_built_lab_inconclusive_study",
      ]),
      ...casesFrom("scorecard metric", [
        "studiesAttempted",
        "studiesCompleted",
        "labNeedsInferred",
        "buildVsBuyDecisions",
        "packagesProvisioned",
        "customInstrumentsBuilt",
        "pipelinesComposed",
        "nodeAlphaExecutions",
        "containerNetoffExecutions",
        "newDomainUsed",
        "realDataOrProxyStudies",
        "reproductionAttempts",
        "instrumentCalibrationUsed",
        "pipelineReplayPassRate",
        "instrumentsReused",
        "labMemoryUpdated",
        "scientificMemoryUpdated",
        "publicCorpusPublications",
        "blockedUnsafeCapabilities",
        "degradedCapabilities",
        "publicLeakCount",
        "criticalFailureCount",
        "readinessLabel",
      ]),
      ...casesFrom("rc gate", [
        "REAL_SOURCE_LAB_TRIAL_PRESENT",
        "FOUR_STUDIES_ATTEMPTED",
        "NEW_DOMAIN_INCLUDED",
        "REAL_DATA_OR_PROXY_USED",
        "REPRODUCTION_ATTEMPT_PRESENT",
        "LAB_NEEDS_INFERRED_FOR_EACH_STUDY",
        "BUILD_VS_BUY_DECISION_FOR_EACH_STUDY",
        "TOOLCHAIN_PROVISIONING_ATTEMPTED",
        "INSTRUMENTS_BUILT_OR_REUSED",
        "INSTRUMENT_CALIBRATION_USED",
        "PIPELINES_COMPOSED",
        "NODE_ALPHA_EXECUTIONS_PRESENT",
        "CONTAINER_NETOFF_EXECUTIONS_PRESENT",
        "BASELINES_PRESENT",
        "STATISTICS_PRESENT",
        "REPLICATIONS_PRESENT",
        "FALSIFICATIONS_PRESENT",
        "LAB_MEMORY_UPDATED",
        "SCIENTIFIC_MEMORY_UPDATED",
        "PUBLIC_HYGIENE_PASSED",
        "NO_RAW_LOGS_OR_SECRETS",
        "NO_LOCAL_PATHS",
        "NO_FAKE_SCIENTIFIC_CLAIMS",
        "NO_DANGEROUS_DOMAIN_CONTENT",
        "CORPUS_AUTOPUBLISH_PASSED_OR_EXPLICITLY_DEGRADED",
      ]),
      ...casesFrom("trial requirement", [
        "at least 6 candidate research questions",
        "at least 4 safe studies attempted",
        "at least 2 studies use real public data or real-data proxy",
        "at least 1 new domain beyond energy/chemistry/patch-risk",
        "at least 1 reproduction attempt",
        "at least 4 lab need inferences",
        "at least 4 build-vs-buy decisions",
        "at least 3 package/tool provisioning attempts",
        "at least 4 custom instruments built or reused",
        "at least 4 pipelines composed",
        "at least 4 Node Alpha executions",
        "at least 2 container-netoff executions",
        "instrument benchmark/calibration used in tool selection",
        "weak studies marked inconclusive/needs_revision/rejected",
        "eligible results autopublished to corpus",
        "no standalone repos created",
      ]),
      ...casesFrom("safety", [
        "No raw logs",
        "No secrets",
        "No local paths",
        "No fake scientific claims",
        "No dangerous domain content",
        "No host sudo",
        "No curl | sh",
        "No silent fallback",
        "safe computational science",
      ]),
      ...casesFrom("publication", [
        "/Users/sovryn/Desktop/sovryn-open-inventions",
        "https://github.com/n57d30top/sovryn-open-inventions",
        "sovryn-lab-autopublish",
        "humanReviewRequired",
        "automatedPolicyVersion",
        "targetPath",
        "pushed",
        "dryRun",
        "publicHygienePassed",
        "noCriticalFailures",
      ]),
      ...casesFrom("version", ["4.2.0-rc.1"]),
    ],
  },
];

for (const week of roadmap) {
  test(`${week.week} has at least ${week.minimum} audit cases`, () => {
    assert.ok(
      week.cases.length >= week.minimum,
      `${week.week} only has ${week.cases.length} audit cases`,
    );
  });

  for (const item of week.cases) {
    test(`${week.week}: ${item.label}`, async () => {
      assert.match(await haystack(), new RegExp(escapeRegExp(item.token), "i"));
    });
  }
}

test("roadmap audit covers the full six-week test minimum", () => {
  const total = roadmap.reduce((sum, week) => sum + week.cases.length, 0);
  assert.ok(total >= 370, `roadmap audit has ${total} cases`);
});

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
